name: optimality-of-word-lengths
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - pylint
  - pip
  - pip:
    - ipdb
    - homoglyphs
